# Generated by Django 5.2.4 on 2026-04-17 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Almaty', max_length=120)),
                ('country', models.CharField(default='Kazakhstan', max_length=120)),
                ('district_name', models.CharField(db_index=True, max_length=120)),
                ('aqi', models.PositiveIntegerField()),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=6)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, default=43.238949, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=76.889709, max_digits=9)),
                ('station_count', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-aqi'],
            },
        ),
        migrations.CreateModel(
            name='AirQualityHistoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aqi', models.PositiveIntegerField()),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_points', to='air_quality.airqualityrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('station_name', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_locations', to='air_quality.airqualityrecord')),
            ],
            options={
                'ordering': ['station_name'],
            },
        ),
    ]
